### ISSUE TITLE
fatal error: no member named 'find_if' in namespace 'std'; did you mean 'finitef'?

### ISSUE THREAD

**Issue by williamleong** [aaron-michaux/munkres-algorithm#1]
Compilation fails with the following:
```
[build] munkres-algorithm/munkres.hpp:72:20: fatal error: no member named 'find_if' in namespace 'std'; did you mean 'finitef'?
[build]          auto ii = std::find_if(cbegin(data), cend(data), [](auto x) {
[build]                    ^~~~~
```
Fix with adding `#include <algorithm>`.

Thanks for a great and clean implementation!

**Comment by aaron-michaux** [comment]
Hi, thanks for pointing this out. Raises the question: why did clang build and run the example. I've patched the code.

**Comment by williamleong** [comment]
Hi, I'm not super sure, but I'm guessing it is because I am compiling using clang in C++14 mode, but now we can be confident it will work in both C++14 and C++17.
